#!/usr/bin/env bash

IMAGE="my_bash_env"
CONTAINER_NAME="${USER}_bash_env"
HOSTNAME="${USER}_custom_bash"
HOME_DIR="/home/dev"

docker run -it --rm \
  --name "${CONTAINER_NAME}" \
  --hostname "${HOSTNAME}" \
  --user "$(id -u):$(id -g)" \
  -e TERM="$TERM" \
  -v $HOME/.ssh:/root/.ssh:ro \
  -v $SSH_AUTH_SOCK:/ssh-agent \
  -e SSH_AUTH_SOCK=/ssh-agent \
  -v "$HOME/.bashrc:$HOME_DIR/.bashrc:ro" \
  -v "$HOME/.vimrc:$HOME_DIR/.vimrc:ro" \
  -v "$HOME/.vim:$HOME_DIR/.vim:ro" \
  -v "$HOME/.gitconfig:$HOME_DIR/.gitconfig:ro" \
  -v "$HOME/Desktop/Code/Bash:$HOME_DIR/Bash" \
  --workdir "$HOME_DIR/Bash" \
  "${IMAGE}"

clear

